# Generated by Django 2.2 on 2021-01-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.CharField(default='1.png', max_length=255),
            preserve_default=False,
        ),
    ]
