# Generated by Django 2.2 on 2021-01-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service_app', '0004_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
